### ISSUE TITLE
usethis release makes a test fail

### ISSUE THREAD

**Issue by jennybc** [rorynolan/exampletestr#10]
We are in the process of releasing usethis v1.6.0.

Although we did not see a problem with exampletestr in our revdep checks, CRAN did. It appears to be due to a brittle test that relies on usethis's user-facing messaging.

I suspect it's due to https://github.com/r-lib/usethis/commit/7af1aa2e0ac0b699fdd39f5cfbe4d1ccba41bc48, where we "Use messages rather than cat to output".

Below is what CRAN's auto-check service shows.

Can you rework your test to pass against dev usethis? I don't think this will hold up the usethis release, but let's fix it soon-ish anyway.  Ideally your tests wouldn't rely on, e.g., the exact behaviour of another package re: messaging.

---

Package: exampletestr
Check: tests
New result: ERROR
    Running â€˜spelling.Râ€™ [0s/0s]
    Running â€˜testthat.Râ€™ [14s/14s]
  Running the tests in â€˜tests/testthat.Râ€™ failed.
  Complete output:
    > library(testthat)
    > library(exampletestr)
    > 
    > get_os <- function() {
    +   sysinf <- Sys.info()
    +   if (!is.null(sysinf)) {
    +     os <- sysinf["sysname"]
    +     if (os == "Darwin") {
    +       os <- "osx"
    +     }
    +   } else { ## mystery machine
    +     os <- .Platform$OS.type
    +     if (grepl("^darwin", R.version$os)) {
    +       os <- "osx"
    +     }
    +     if (grepl("linux-gnu", R.version$os)) {
    +       os <- "linux"
    +     }
    +   }
    +   if (os == "osx") os <- "mac"
    +   tolower(os)
    + }
    > 
    > if (get_os() != "mac" || Sys.getenv("NOT_CRAN") == "true")
    +   test_check("exampletestr")
    â”€â”€ 1. Failure: `make_tests_shells_file()` and `make_tests_shells_pkg()` work (@t
    capture.output(make_tests_shells_pkg(pkg_dir, document = FALSE)) is empty.
    
    â•â• testthat results  â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
    [ OK: 27 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 1 ]
    1. Failure: `make_tests_shells_file()` and `make_tests_shells_pkg()` work (@test-files.R#81) 
    
    Error: testthat unit tests failed
    Execution halted

**Comment by rorynolan** [comment]
This is actually great. Now I can use `expect_message()` rather than `expect_match(capture.output())` and indeed create a much better test. Crack on with `usethis` v1.6.0, looking forward to the release :-)

**Comment by jennybc** [comment]
Ideally you would still devise a test that's more about the outcome of something your package does than about our message.

It's not a big surprise that our switch away from `cat()` had some downstream effects. But it would be nice if, in future, we tweak wording of a message, we don't end up here again.

**Comment by rorynolan** [comment]
I get that from your point of view. From my point of view, I like usethis' messaging (e.g. `ui_path()`) and in this particular package `exampletestr`, messaging is very important, and if it changes, I'd like to be notified to make sure my package's messaging still makes sense. Up until now, I was using CRAN checks for this. However I realise now that this is annoying for you. 
Here's what I'll do:
I'll skip these message checks on CRAN and have Travis build my package daily, using the dev usethis. That way I'll get notified but you won't have to worry about this anymore.
I love usethis and the last thing I want to do is frustrate its development.

**Comment by jennybc** [comment]
Given your goals, I think you should look into `testthat::verify_output()`. It keeps you very aware of any changes we make that affect your package, but it will never fail *on CRAN*.

https://testthat.r-lib.org/reference/verify_output.html

https://www.tidyverse.org/blog/2019/11/testthat-2-3-0/#verify_output

**Comment by rorynolan** [comment]
That's great, I didn't know about `verify_output()` and I will use it.
Thanks so much Jenny.

**Comment by rorynolan** [comment]
This fix (using `testthat::verify_output()`) is now on CRAN and I'm making my travis build daily with dev `usethis` to catch this kind of thing in future before it bothers you.
All the best :-)

**Comment by jennybc** [comment]
Great! Thanks.
