### ISSUE TITLE
One of your tests fails due to updates in a usethis error message

### ISSUE THREAD

**Issue by jennybc** [rorynolan/exampletestr#13]
I'm about to do a major update of usethis and one of the main changes is an overhaul of its UI to use cli instead of homegrown functions.

As a result many of usethis's messages, including error messages, are a bit different.

This release is going to break one of your tests that has very specific expectations about a usethis error message. I would advise against checking someone else's error message like this. (If it's any consolation, I recently has a similar experience in reprex, where I had a brittle test around a base R error message 😬 )

Here's the failure that I see in my revdepchecks:

```
`extract_examples("detect", tempdir(check = TRUE))` threw an error with unexpected message.
Expected match: "Path .+ does not appear to be inside a project or package."
Actual message: "✖ Path '/private/tmp/RtmpKxS38z/' does not appear to be inside a project\n  or package.\nℹ Read more in the help for `usethis::proj_get()`."
```

**Comment by mirvie-bfx-code** [comment]
Thank you @jennybc 
I'm fixing this now and won't fail on CRAN for this reason again.

**Comment by rorynolan** [comment]
Thank you @jennybc 
I've fixed it and won't fail for this reason on CRAN in future.
