### ISSUE TITLE
Allow specification of function names instead of files similar to make_tests_shells_file

### ISSUE THREAD

**Issue by lorenzwalthert** [rorynolan/exampletestr#6]
Looks like an interesting package. A function like `make_tests_shells_fun()` could be useful if one has several declarations of functions in an R script and want's to add tests for one at a time.

**Comment by rorynolan** [comment]
Hi Lorenz,
That's a good idea. I'll try to implement this in the next few days.
If I haven't done it within 2 weeks, feel free to remind me. I promise I won't get mad.
Thanks for your interest,
Rory

**Comment by lorenzwalthert** [comment]
Cool. How do you plan to approach it? I think you could use parse data to find the function declaration in a clean way. Using something along these lines. 
```r
utils::getParseData(parse(path))
```
To find the the path to the function declaration, you could also use my package [parsesum](https://github.com/lorenzwalthert/parsesum). However, I can't promise that it will be on CRAN soon.

**Comment by rorynolan** [comment]
For now, I'm going to use the same methods as are used in `exampletestr::extract_examples()`. These are dirty and I'm not proud of them, but they've worked fine so far. I would love to use `parsesum` but until it's on CRAN, I can't (because `exampletestr` must depend on CRAN packages only to be viable for CRAN). Please let me know when `parsesum` is on CRAN. It would be very useful for cleaning up the internal code in `exampletestr`.

**Comment by rorynolan** [comment]
Hi @lorenzwalthert,
I've implemented `make_test_shell_fun()` now. Would you please install the new version with `devtools::install_github("rorynolan/exampletestr")` and give it a test run?
Much appreciated,
Rory

**Comment by rorynolan** [comment]
Hi @lorenzwalthert,
Do you think you'll have time to try this out? If not I think it's working well and I'm happy to close the issue.

**Comment by lorenzwalthert** [comment]
Thanks @rorynolan. I guess I should but I can only do it next week at earliest. Is it merged into master already?

**Comment by rorynolan** [comment]
Yes @lorenzwalthert, it's part of master. Take all the time you need. I'll probably push the current update to CRAN in a couple of weeks but even if you take longer than that it's fine, I'd appreciate your input and incorporate it for the following release.

**Comment by rorynolan** [comment]
Hey @lorenzwalthert I'm gonna push this update to CRAN now and close the issue. I'm satisfied that it's working now, have been using it myself recently :)
Thanks for the input.
If you use it yourself and have a bug or feature request, feel free to comment below or open a new issue.

**Comment by lorenzwalthert** [comment]
Thanks, and sorry I have not had time to test it.
