### ISSUE TITLE
Test failure with dev usethis (v1.4.0.9000)

### ISSUE THREAD

**Issue by jennybc** [rorynolan/exampletestr#8]
Similar content to the email, but if we need to correspond, probably better to do it here.

In preparation for an upcoming usethis release, I did revdep checks and there is a new test failure in exampletestr:

https://github.com/r-lib/usethis/blob/master/revdep/problems.md#exampletestr

Currently my suspicion is that this may be related to your tests not restoring state before they exit. Specifically, making sure that usethis active project, working directory, and file system are the same at the end as at the start. usethis requires some care to test and you are inheriting some of this fiddliness. You might want to look at the `scoped_temporary_package()` helper we've created for ourselves here:

https://github.com/r-lib/usethis/blob/master/tests/testthat/helper.R

We use that extensively in our tests to solve similar problems. You probably need to create a similar helper for yourself or do the same restoration "by hand".

**Comment by rorynolan** [comment]
Hi Jenny,
Im currently on holiday so won't be able to fix this for 2 weeks yet
(didn't bring my laptop with me 😊). Thanks for your idea of how to fix the
problem, that's certainly the way I'll tackle it.
If you need to submit usethis before I fix exampletestr, no worries.
Thanks for all your great work in R as a teacher, user and developer.
Rory

**Comment by jennybc** [comment]
OK thanks for letting me know. We may indeed try to release in less than 2 weeks, so it's helpful for us to have had this conversation. Let me know if you have any questions when you sit down to sort this out.

**Comment by rorynolan** [comment]
This is sorted now. I was relying on a mixture of rprojroot and usethis and it was a bit messy. Now I just use `usethis::proj_*()` everywhere and it's all fine.
